---
- name: Restarting Server
  reboot:

- name: Do Pinging
  ping:

- name: Installing Pre-requisities 
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - wget
      - device-mapper-persistent-data
    state: present 

- name: Disable Firewalld
  systemd:
    name: firewalld
    enabled: no

- name: Stop Firewalld
  service:
    name: firewalld
    state: stopped

- name: Disable SELinux 1/2
  shell: setenforce 0

- name: Disable SELinux 2/2
  replace:
    path: /etc/sysconfig/selinux
    regexp: '^SELINUX=enforcing'
    replace: 'SELINUX=disabled'
  
- import_tasks: ../../utils.yaml
  vars:
    role_status: 'preflight'






  



