---
  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo

  - name: Enable Docker Edge repo
    ini_file:
      dest: /etc/yum.repos.d/docer-ce.repo
      section: 'docker-ce-edge'
      option: enabled
      value: '0'

  - name: Enable Docker Test repo
    ini_file:
      dest: /etc/yum.repos.d/docer-ce.repo
      section: 'docker-ce-test'
      option: enabled
      value: '0'

  - name: Installing Docker
    yum:
      name:
        - docker-ce
      state: present

  - name: Systemd Docker enable
    systemd:
      name: docker
      enabled: yes

  - name: Systemd Docker start
    service:
      name: docker
      state: started

  - name: Appendig User Vagrant to Docker
    user:
      name: vagrant
      groups: docker
      append: yes
  
  - name: Reload SysCtl  net.bridge.bridge-nf-call-ip6tables
    sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: '1'
      reload: no
    
  - name: Reload SysCtl  net.bridge.bridge-nf-call-iptables
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: '1'
      reload: yes

  - import_tasks: ../../utils.yaml
    vars:
      role_status: 'installDocker'