---
- hosts: k8sservers
  remote_user: root
  vars:
    k8s_status: {}
  tasks:
    - name: ROLE-> Check Status Process
      include_role:
        name:  checkStatus

    - name: ROLE-> Installing PreFlight Conditions
      include_role:
        name:  preflight
      when:  not k8s_status.preflight

    - name: ROLE-> Installing Docker
      include_role:
        name:  installDocker
      when: not k8s_status.installDocker

    - name: ROLE-> Installing Kubeadm
      include_role:
        name:  installKubeadm
      when: not k8s_status.installKubeadm

## Configuring KubeAdmin, and CALICO in Master and Nodes
- hosts: k8smaster
  remote_user: root
  tasks:
    - name: ROLE-> Configuring KubeAdmin
      include_role:
        name:  configureKubeadm
      when: not k8s_status.configureKubeadm

    
- hosts: k8snode1 k8snode2
  remote_user: root
  tasks:
    - name: Get Token from Master
      command: kubeadm token create --print-join-command 
      delegate_to: k8smaster
      register:  token_out
      when: not k8s_status.configureKubeadm

    - name: Adding Nodes
      command: "{{ token_out.stdout }}"
      when: not k8s_status.configureKubeadm


