---
  - name: Check that the somefile.conf exists
    stat:
      path: /opt/status_k8s.json
    register: stat_result

  - set_fact:
      k8s_status:
        preflight: false
        installDocker: false
        installKubeadm: false
        configureKubeadm: false
    when: not stat_result.stat.exists

  - name: Create Status File
    copy:
      dest: /opt/status_k8s.json
      content: "{{ k8s_status | to_nice_json }}"
    when: not stat_result.stat.exists

  - name: Read Status Project 1/3
    shell: cat /opt/status_k8s.json
    register: k8s_status
  
  - name: Read Status Project 2/3
    set_fact:
      k8s_status: "{{ k8s_status.stdout | from_json }}"


  

